version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing serverless framework
      - npm install -g serverless
  pre_build:
    commands:
      - echo install pre build commands
  build:
    commands:
      - echo Installing NPM Packages
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Entering Post_Build Phase
      - aws lambda update-function-code \--function-name  Dummy \--s3-bucket codepipeline-us-east-1-802277446442 --s3-key Build.zip
artifacts:
  files:
    - "**/*"
